'use client';

import React, { useState } from 'react';

interface Product {
  id: number;
  icon: string;
  title: string;
  price: string;
  priceSubtext: string;
  description: string;
}

interface Feature {
  id: number;
  title: string;
  description: string;
}

interface Stat {
  id: number;
  number: string;
  description: string;
}

interface FooterSection {
  title: string;
  links: string[];
}

export default function SquareLanding() {
  const [hoveredProduct, setHoveredProduct] = useState<number | null>(null);

  const products: Product[] = [
    {
      id: 1,
      icon: '📱',
      title: 'The sleek, dual-screen system',
      price: '$799',
      priceSubtext: 'or $39/mo. over 24 months',
      description: 'Advanced POS system with dual displays for maximum efficiency in any business environment.',
    },
    {
      id: 2,
      icon: '🏪',
      title: 'The POS that moves with you',
      price: '$399',
      priceSubtext: 'or $37/mo. over 12 months',
      description: 'Portable and powerful POS system designed for businesses on the go.',
    },
    {
      id: 3,
      icon: '🧾',
      title: 'The receipt-printing POS',
      price: '$299',
      priceSubtext: 'or $27/mo. over 12 months',
      description: 'Reliable point of sale system with integrated receipt printing capabilities.',
    },
    {
      id: 4,
      icon: '📲',
      title: 'The intuitive, swiveling iPad POS',
      price: '$149',
      priceSubtext: 'or $14/mo. over 12 months',
      description: 'Flexible iPad-based POS system with intuitive interface for quick transactions.',
    },
  ];

  const features: Feature[] = [
    {
      id: 1,
      title: '💳 Take payments',
      description: 'Sell anything in person and online with a point of sale platform that works for whatever you sell.',
    },
    {
      id: 2,
      title: '👥 Manage your team',
      description: 'Run payroll, schedule shifts, and take care of admin — so your team can focus on performing their best.',
    },
    {
      id: 3,
      title: '📈 Grow your customer base',
      description: 'Set up the right marketing campaigns and loyalty program to welcome new customers and keep them coming back.',
    },
    {
      id: 4,
      title: '💰 Control your cash flow',
      description: 'Bring your revenue under one roof. Instantly access your funds and get quicker access to loans.',
    },
    {
      id: 5,
      title: '🔌 Connect your apps',
      description: 'Square partners with hundreds of apps so you can manage your entire business without jumping between platforms.',
    },
    {
      id: 6,
      title: '🤖 Square AI',
      description: 'Ask Square AI anything about your business to get immediate insights and make smart decisions, fast.',
    },
  ];

  const stats: Stat[] = [
    {
      id: 1,
      number: '500M+',
      description: 'food and beverage sellers using Square globally',
    },
    {
      id: 2,
      number: '$2T+',
      description: 'generated by retailers using Square annually',
    },
    {
      id: 3,
      number: '100M+',
      description: 'appointments booked through Square every month',
    },
    {
      id: 4,
      number: '$1.5B+',
      description: 'paid with invoices globally',
    },
  ];

  const footerSections: FooterSection[] = [
    {
      title: 'Products',
      links: ['Point of Sale', 'Payments', 'Invoicing', 'Payroll'],
    },
    {
      title: 'Solutions',
      links: ['Restaurants', 'Retail', 'Services', 'Online'],
    },
    {
      title: 'Company',
      links: ['About', 'Careers', 'Press', 'Investors'],
    },
    {
      title: 'Support',
      links: ['Help Center', 'Community', 'Contact Us', 'Status'],
    },
  ];

  return (
    <div className="min-h-screen bg-white text-gray-900">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 bg-white/95 backdrop-blur-xl z-50 border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <a href="#" className="text-2xl font-bold text-gray-900 tracking-tight">Square</a>
          <nav className="hidden md:flex gap-12 items-center">
            <a href="#products" className="text-sm font-medium text-gray-900 hover:text-indigo-600 transition">Products</a>
            <a href="#features" className="text-sm font-medium text-gray-900 hover:text-indigo-600 transition">Features</a>
            <a href="#pricing" className="text-sm font-medium text-gray-900 hover:text-indigo-600 transition">Pricing</a>
            <a href="#about" className="text-sm font-medium text-gray-900 hover:text-indigo-600 transition">About</a>
            <button className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-semibold hover:bg-indigo-700 transition transform hover:-translate-y-0.5 shadow-lg hover:shadow-lg">
              Get Started
            </button>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative h-screen flex items-center justify-center overflow-hidden mt-16">
        <video className="absolute top-0 left-0 w-full h-full object-cover z-10" autoPlay muted loop playsInline>
          <source src="https://pw-assets-production-c.squarecdn.com/video/5mObdhW0r5D0lyp3iVJFA6/b4d81931-7cfa-4402-bb41-efc4126e3f95-en-ee526a6b-3ca3-4ae5-9bc2-be60cb21229f-en-Homepage_Edit-updated.webm" type="video/webm" />
          Your browser does not support the video tag.
        </video>
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-gray-900/40 to-gray-900/20 z-20"></div>
        <div className="relative z-30 text-center text-white max-w-2xl px-6">
          <h1 className="text-6xl md:text-7xl font-bold mb-6 leading-tight tracking-tight">Power your entire business</h1>
          <p className="text-xl md:text-2xl mb-12 font-light opacity-95">Everything you need to run your business in one place. From payments to payroll, Square has you covered.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center flex-wrap">
            <button className="px-8 py-3 bg-white text-indigo-600 rounded-lg font-semibold hover:bg-gray-100 transition transform hover:-translate-y-0.5 shadow-xl hover:shadow-2xl">
              Start Free Trial
            </button>
            <button className="px-8 py-3 border-2 border-white text-white rounded-lg font-semibold hover:bg-white/10 transition">
              Watch Demo
            </button>
          </div>
        </div>
      </section>

      {/* Products Section */}
      <section className="py-24 px-6 bg-gray-50" id="products">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-5xl md:text-6xl font-bold mb-4 leading-tight">Smooth checkout, every time</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">Choose from a range of sleek options for however you do business. All equally easy to use.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {products.map((product) => (
              <div
                key={product.id}
                className="bg-white p-8 rounded-2xl border border-gray-200 transition transform hover:-translate-y-2 hover:shadow-2xl cursor-pointer"
                onMouseEnter={() => setHoveredProduct(product.id)}
                onMouseLeave={() => setHoveredProduct(null)}
              >
                <div className="text-4xl mb-4">{product.icon}</div>
                <h3 className="text-xl font-semibold mb-4 text-gray-900">{product.title}</h3>
                <div className="text-3xl font-bold text-indigo-600 mb-2">{product.price}</div>
                <p className="text-sm text-gray-600 mb-4">{product.priceSubtext}</p>
                <p className="text-gray-600 text-sm leading-relaxed mb-6">{product.description}</p>
                <button className="w-full px-4 py-3 bg-indigo-600 text-white rounded-lg font-semibold hover:bg-indigo-700 transition">
                  Learn More
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 px-6 bg-white" id="features">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-5xl md:text-6xl font-bold mb-4 leading-tight">See your whole business click into place</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">Comprehensive tools to manage every aspect of your business.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => (
              <div key={feature.id} className="p-8 rounded-2xl bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 border border-gray-200">
                <h3 className="text-xl font-semibold mb-4 text-gray-900">{feature.title}</h3>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-24 px-6 bg-gradient-to-r from-gray-900 to-gray-800 text-white">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-12">
            {stats.map((stat) => (
              <div key={stat.id}>
                <h4 className="text-5xl font-bold mb-2">{stat.number}</h4>
                <p className="text-lg opacity-95 font-light">{stat.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 bg-gradient-to-r from-indigo-600 to-indigo-700 text-white text-center">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-5xl md:text-6xl font-bold mb-6 leading-tight">Ready to transform your business?</h2>
          <p className="text-xl mb-10 opacity-95">Join thousands of businesses already using Square to grow and succeed.</p>
          <button className="px-10 py-4 bg-white text-indigo-600 rounded-lg font-semibold hover:bg-gray-100 transition transform hover:-translate-y-0.5 text-lg shadow-xl">
            Start Your Free Trial
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-16 px-6">
        <div className="max-w-7xl mx-auto mb-8">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
            {footerSections.map((section, index) => (
              <div key={index}>
                <h4 className="font-semibold mb-4 text-white">{section.title}</h4>
                {section.links.map((link, linkIndex) => (
                  <a key={linkIndex} href="#" className="text-gray-400 text-sm hover:text-white transition block mb-3">
                    {link}
                  </a>
                ))}
              </div>
            ))}
          </div>
          <div className="border-t border-gray-800 pt-8 text-center text-gray-400 text-sm">
            <p>&copy; 2026 Square, Inc. All rights reserved. | Privacy | Terms | Accessibility</p>
          </div>
        </div>
      </footer>
    </div>
  );
}